version: "3.8"
services:
  storybook:
    # Dockerfileビルド
    build: ./vercel
    # ディレクトリを共有する。
    volumes:
      - ../stories:/app/internals/component-catalog/stories
      - ../.storybook:/app/internals/component-catalog/.storybook
      - ../../../src:/app/src
      - ../../../public:/app/public
      - ../../../vercel.json:/app/vercel.json
      - ../../../next.config.js:/app/next.config.js
      - ../../../.vercelignore:/app/.vercelignore
      - ../../../tsconfig.json:/app/tsconfig.json
      - ../../../.eslintrc.js:/app/.eslintrc.js
      - ../../../.gitignore:/app/.gitignore
      - ../../../.babelrc.js:/app/.babelrc.js
      - ../../../.prettierrc.js:/app/.prettierrc.js
      - ../dist:/app/dist
    ports:
      - 6006:6006
    # environment:
    #   - CHOKIDAR_USEPOLLING=true # デフォルトの設定の場合、vagrantだとファイルの変更を検知できない。pollingが必要。 -> webpack5からchokidar不使用
    working_dir: /app
    command: [npx, start-storybook, -c, '/app/internals/component-catalog/.storybook', -p, '6006']

