version: "3.8"
services:
  openapi:
    # Dockerfileビルド
    build: ./node
    # ディレクトリを共有する。
    volumes:
      - ../openapi.yml:/app/openapi.yml
      - ../components:/app/components
      - ../paths:/app/paths
      - ../../../src/types/openapi:/app/dist
    # ports:
    #   - 6006:6006
    # environment:
    #   - CHOKIDAR_USEPOLLING=true # デフォルトの設定の場合、vagrantだとファイルの変更を検知できない。pollingが必要。 -> webpack5からchokidar不使用
    working_dir: /app
    # command: [npx, start-storybook, -p, '6006']

