name: github pages

on:
  push:
    branches:
      - docs  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: OpenAPI Setup
        run: npm ci
        working-directory: ./internals/api-schema

      - name: OpenAPI Make
        run: npm run redoc
        working-directory: ./internals/api-schema


      - name: OpenAPI Move files
        run: |
          mkdir -p ./docs/publish/api-schema
          mv ./internals/api-schema/dist/index.html ./docs/publish/api-schema/

      - name: StoryBook Setup
        run: npm ci
        working-directory: ./internals/component-catalog

      - name: StoryBook Setup for ~bootstrap.scss
        run: npm i bootstrap@next

      - name: StoryBook Make
        run: npx build-storybook -c ./.storybook -o ./component-catalog --no-dll
        working-directory: ./internals/component-catalog

      - name: StoryBook Move files
        run: |
          mkdir -p ./docs/publish/component-catalog
          mv ./internals/component-catalog/component-catalog ./docs/publish/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
